---
- hosts: all
  tasks:
    - name: Ensure kubeadm-bin is installed
      pacman:
        name: kubeadm-bin
      become: yes

    - name: Ensure kubelet-bin is installed
      pacman:
        name: kubelet-bin
      become: yes

    - name: Download kubectl binary to /opt
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/arm/kubectl
        dest: /opt/kubectl
      become: yes

    - name: Update permissions of kubectl binary
      file:
        path: /opt/kubectl
        mode: 0775
        owner: jjaniec
        group: wheel
      become: yes

    - name: Ensure required packages are installed
      pacman:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - ethtool
        - ebtables
        - socat

    - name: Enable kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: yes
      become: yes
