---
- hosts: all
  tasks:
    - name: Ensure locales are set to en_US.UTF-8
      lineinfile:
        path: /etc/locale.gen
        regexp: "^en_US.UTF-8 UTF-8"
        line: en_US.UTF-8 UTF-8
      become: yes

    - name: Generate locales
      shell: locale-gen
      become: yes
