---
# - name: Ensure base packages are installed
#   pacman:
#     name: "{{ packages }}"
#     state: present
#   become: yes

- name: Add custom users
  user:
    name: "{{ item }}"
    password: "{{ users_password[i] | password_hash('sha512') }}"
    shell: /bin/zsh
  loop: "{{ custom_users }}"
  loop_control:
    index_var: i
  become: yes

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: yes

- name: Add custom users to wheel group
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
  loop: "{{ custom_users }}"
  become: yes

- name: Add alarm user to wheel group
  user:
    name: alarm
    groups: wheel
    append: yes
    state: present
  become: yes

- name: Add dotfiles role
  include_role:
    name: "{{ ANSIBLE_ROLES }}/dotfiles"
  vars:
    dir_owner: root
    dir_group: wheel
    dir_mode: 0775
    non_root_users:
      - jjaniec
      - alarm

- name: Add pikaur role
  include_role:
    name: "{{ ANSIBLE_ROLES }}/pikaur"

- name: Add podman role
  include_role:
    name: "{{ ANSIBLE_ROLES }}/podman"
  vars:
    PODMAN_DEFAULT_RUNTIME: "crun"

- name: Add telegraf-container role
  include_role:
    name: "{{ ANSIBLE_ROLES }}/telegraf-container"
  vars:
    INFLUX_TOKEN: "{{ influxdbcloud_token }}"
    INFLUX_CONFIG_URL: "{{ influxdbcloud_config_url }}"
    METHOD: "podman"

- name: Add k3s role
  include_role:
    name: "{{ ANSIBLE_ROLES }}/k3s"
  vars:
    K3S_DOWNLOAD_URL: "https://github.com/rancher/k3s/releases/download/v1.0.0/k3s-armhf"
